### ISSUE TITLE
TypeError on Theta Structure Instantiation

### ISSUE THREAD

**Issue by evank28** [UltraSpecialException/CSC401A3-GMM-Autotester#1]
When running the student tests i get the following error:
`C:\Users\evank\.virtualenvs\A3\Scripts\python.exe C:/Users/evank/wdenv/University/csc401/A3/test/student_tests.py --structured --gmm ../a3_gmm_structured.py
Traceback (most recent call last):
  File "C:/Users/evank/wdenv/University/csc401/A3/test/student_tests.py", line 137, in <module>
    params = gmm_mod.theta("Test Theta", data, 8, 13)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

Process finished with exit code 1
`

I believe this is because on line 137 we are passing `data` to the theta constructor, when this argument is not expected.

**Comment by UltraSpecialException** [comment]
Thanks for pointing that out! My bad. I had fixed that. And sorry I didn't see your pull request until just now. I can still merge it, probably.
